### ISSUE TITLE
Disconnected Radiators Crash Homebridge

### ISSUE THREAD

**Issue by vultuk** [eirikeikaas/homebridge-adax#2]
**Describe The Bug:**
When a radiator is disconnected, for example unplugged or lost WIFI connection Homebridge Crashes.

**To Reproduce:**
Disconnect a Radiator from the power / wifi.

**Expected behavior:**
The radiator should show as offline

**Logs:**

```TypeError: Cannot read property 'toFixed' of undefined
    at ADAXPlatformAccessory.precision (/usr/local/lib/node_modules/homebridge-adax/src/platformAccessory.ts:64:30)
    at ADAXPlatformAccessory.heatingState (/usr/local/lib/node_modules/homebridge-adax/src/platformAccessory.ts:72:24)
    at ADAXPlatformAccessory.handleTargetHeatingCoolingStateGet (/usr/local/lib/node_modules/homebridge-adax/src/platformAccessory.ts:86:25)
    at Characteristic.emit (events.js:314:20)
    at Characteristic.EventEmitter.emit (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/EventEmitter.ts:42:22)
    at Characteristic._this.getValue (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:489:12)
    at /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:1239:22
    at Array.forEach (<anonymous>)
    at Bridge.Accessory._this._handleGetCharacteristics (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:1167:10)
    at HAPServer.emit (events.js:314:20)
[12/8/2020, 8:26:03 AM] Got SIGTERM, shutting down Homebridge...```

**Comment by vultuk** [comment]
The bug appears to be in this line...

[platformAccessory.ts:64](https://github.com/eirikeikaas/homebridge-adax/blob/732b589f242a7776b9fddeb6e0928bc02e292309/src/platformAccessory.ts#L64)

As `number` is `undefined` it isn't possible to run the `.toFixed()` function.

On my local machine I have simply changed this line to 

```return !number ? 0 : parseFloat(number.tofixed(1));```

Which has temporarily 'solved' the problem by showing offline radiators as 0 degrees. However I believe something more permanent is required.

**Comment by vultuk** [comment]
I have submitted a pull request which should implement a fix for this issue. With this change the heater is marked as 'OFF' if it can't be connected to. 

![image](https://user-images.githubusercontent.com/271838/101480115-24f07180-394b-11eb-89b4-09c1164ade90.png)

**Comment by eirikeikaas** [comment]
Nice 👌
